# Generated by Django 3.1.7 on 2021-04-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='None', max_length=200)),
                ('account_number', models.CharField(default='None', max_length=200)),
                ('emp_name', models.CharField(default='None', max_length=200)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
