# Generated by Django 3.1.7 on 2021-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankadvice', '0003_auto_20210421_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankadvice',
            name='id',
        ),
        migrations.AddField(
            model_name='bankadvice',
            name='emp_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankadvice',
            name='emp_id',
            field=models.CharField(default='None', max_length=200, primary_key=True, serialize=False),
        ),
    ]
