# Generated by Django 3.1.7 on 2021-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210405_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_ac',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
