# Generated by Django 3.1.7 on 2021-04-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210418_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dor',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
