# Generated by Django 3.1.7 on 2021-04-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210420_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dor',
            field=models.CharField(default='68', max_length=200),
        ),
    ]
