# Generated by Django 3.1.7 on 2021-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210421_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='increment',
            field=models.IntegerField(default=0),
        ),
    ]
