# Generated by Django 3.1.7 on 2021-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20210405_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='None', max_length=200)),
                ('name', models.CharField(default='None', max_length=200)),
                ('net_salary', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
