# Generated by Django 3.1.7 on 2021-04-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210418_1530'),
        ('calculation', '0002_auto_20210418_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.qualification'),
        ),
    ]
