# Generated by Django 3.1.7 on 2021-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20210418_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='qualification',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
