# Generated by Django 3.1.7 on 2021-04-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210420_1330'),
        ('calculation', '0004_auto_20210418_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.qualification'),
        ),
    ]
